ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/msm_vb2
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/camera
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += cci/ io/ csiphy/ csid/ actuator/ eeprom/ ois/ flash/ LC898123/
obj-$(CONFIG_MSM_CAMERA_SENSOR) += msm_sensor_init.o msm_sensor_driver.o msm_sensor.o
