ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/sensor/cci
obj-$(CONFIG_MSMB_CAMERA) += msm_actuator.o
