ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/isp/
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/common
obj-$(CONFIG_MSM_CPP) += msm_cpp.o
