ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2_nubia/sensor/io
obj-$(CONFIG_MSM_CCI) += msm_cci.o
